### ISSUE TITLE
Allow hot keys from input fields?

### ISSUE THREAD

**Issue by mklbtz** [jaywcjlove/react-hotkeys#11]
There doesn't seem to be a way to configure this to handle events when an input is selected. I read the source code a bit and it seems like this is intentional, but I'm wondering if you have plans to support it? 

My use case is: I would like to allow users to hit `esc` from a search box to dismiss & hide the search box. Similar to GitHub's new search box: hit "S" to activate search, hit escape to deactivate.

I'm not exactly sure how these scope things work, but it seems like this is what prevents hotkeys from activating from inputs:
https://github.com/jaywcjlove/react-hotkeys/blob/fab7c648f5fdbb89e54c44598ef335339fb51a76/src/index.js#L5-L9

**Comment by jaywcjlove** [comment]
### filter

`INPUT` `SELECT` `TEXTAREA` default does not handle. `filter` to return to the true shortcut keys set to play a role, flase shortcut keys set up failure. Reference [hotkeys](https://github.com/jaywcjlove/hotkeys/blob/01a2650700d4c39b5368f6139a1e83f242eefc37/README.md#filter) documentation.

```diff
<Hotkeys 
  keyName="shift+a,alt+s" 
+  filter={(event) => {
+    return true;
+  }}
  onKeyDown={this.onKeyDown.bind(this)}
  onKeyUp={this.onKeyUp.bind(this)}
/>
```

**Comment by mklbtz** [comment]
That's perfect! Thank you so much for the speedy response. ❤️

**Comment by REX500** [comment]
I just want to comment not because I agree or disagree with anything here but because I have never read a more twisted, messed up, "no logic put into it" description. Seriously Hotkeys people??? Have you read that little block of text?  "default does not handle" - what the hell should that supposed to mean?? "filter to return to the true shortcut keys set to play a role" - why would you use commas or any logic when writing documentation that others will depend on? I remember when I needed this feature, I had to spend hours searching through the web trying to find another person who implemented it and explained it themselves because their description didn't make any sense what so ever.
Other then that, good job guys with the whole Hotkeys thing! My team uses it and we are happy because of it (well, mostly...)!

**Comment by jaywcjlove** [comment]
@REX500 

Sorry, My English is pretty limited. I helped me understand and answer questions through Google Translate. This maybe have inaccurate answers.
